FROM argnctu/pokingbot-rl:rtx30

#  environment
ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV ROS_DISTRO melodic

# install related package
RUN apt-key del 7fa2af80
RUN apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/3bf863cc.pub

RUN apt-get -o Acquire::ForceIPv4=true update && apt-get -o Acquire::ForceIPv4=true install --no-install-recommends -y \
    ros-$ROS_DISTRO-dynamixel-sdk \
    ros-melodic-moveit-* \
    ros-melodic-smach \
    ros-melodic-smach-ros \
    ros-melodic-executive-smach \
    ros-melodic-smach-viewer

RUN pip3 install gdown==4.5.1 

RUN apt install -y zip

# Download model
RUN cd ~/ \
    && mkdir model \
    && cd model \
    && gdown https://drive.google.com/uc?id=1__uGGmoJhg5xI_8okn9Ac-P1Fl7OdTuZ \
    && unzip pokingbot.zip \
    && gdown https://drive.google.com/uc?id=1fnXkbar2pjV8VFlxrjdIgUPZpjGAgFuR \
    && unzip rl_oa.zip